<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="511ms"
		durationms="511"
		type="root"
		rid="248b6d804029e984"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		user="User"
		rxversion="7.2.0.0"
		host="DESKTOP-H3D7L8R"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="uk-UA"
		dtnlanguage="uk-UA"
		screenresolution="1920x1080"
		timestamp="10.10.2017 15:43:30"
		timestampiso="2017-10-10T12:43:30"
		endtime="10.10.2017 15:43:30"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<item
			timeRelativeToTestSuiteStartTime="00:00.511"
			timeRelativeToTestModuleStartTime="00:00.519"
			timeWallClock="15:43:30"
			time="00:00.511"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
